---
title: "Mini-Project 2"
author: "Roshni and Ariel"
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---


## Loading the data



```{r echo = FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
#change1
```




```{r}
contributions2 <- contributions %>% 
  group_by(cand_id) %>% 
  summarize(transaction_amt = sum(transaction_amt))
candidates_and_contributions <- house_elections %>%
  left_join(contributions2, house_elections, by = c("fec_id" = "cand_id"))
```


```{r }
newcandidates_df <- candidates_and_contributions %>%
filter(incumbent == FALSE, ge_winner != "") %>%
  group_by(ge_winner) %>%
  mutate(party2 = case_when(
    party != "R" & party != "D" ~ "Ind", TRUE ~ party
  )) %>%
  group_by(ge_winner, party2) %>%
  summarize(total = n(), avg_funding = mean(transaction_amt, na.rm = TRUE))
  
incumbents_df <- candidates_and_contributions %>%
filter(incumbent == TRUE, ge_winner != "") %>%
  group_by(ge_winner) %>%
  mutate(party2 = case_when(
    party != "R" & party != "D" ~ "Ind", TRUE ~ party
  )) %>%
  group_by(ge_winner, party2) %>%
  summarize(total = n(), avg_funding = mean(transaction_amt, na.rm = TRUE)) 
```
 

```{r}
newcandidates_plot <- ggplot(newcandidates_df, aes(x = party2, y = total, fill = party2, label = avg_funding)) +
  scale_fill_manual(values = c("blue", "green", "red")) +
  labs(fill = "") +
  xlab("Party") +
  ylab("Number of Candidates") +
  ggtitle("New Candidates, Winners and Losers Across Each Party") +
  geom_bar(stat = "identity") +
  geom_label_repel(fill= "white") +
  facet_wrap(~ge_winner)

incumbents_plot <- ggplot(incumbents_df, aes(x = party2, y = total, fill = party2, label = avg_funding)) +
  scale_fill_manual(values = c("blue", "green", "red")) +
  labs(fill = "") +
  xlab("Party") +
  ylab("Number of Candidates") +
  ggtitle("Incumbents, Winners and Losers Across Each Party") +
  geom_bar(stat = "identity") +
  geom_label_repel(fill= "white") +
  facet_wrap(~ge_winner)
incumbents_plot
newcandidates_plot
```




